server:
  port: 8083

spring:
  datasource:
    url: jdbc:postgresql://customer-db:5432/${CUSTOMER_DB_NAME}
    username: ${CUSTOMER_DB_USER}
    password: ${CUSTOMER_DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

management:
  endpoints:
    web:
      exposure:
        include: health,info