server:
  port: 8083

spring:
  datasource:
    url: jdbc:postgresql://customer-db:5432/${CUSTOMER_DB_NAME}
    username: ${CUSTOMER_DB_USER}
    password: ${CUSTOMER_DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false

auth-service:
  url: http://auth-service:8086

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URI:http://discovery-service:8761/eureka}
  instance:
    prefer-ip-address: true

management:
  endpoints:
    web:
      exposure:
        include: health,info