server:
  port: 8082

spring:
  datasource:
    url: jdbc:postgresql://deployment-db:5432/${DEPLOYMENT_DB_NAME}
    username: ${DEPLOYMENT_DB_USER}
    password: ${DEPLOYMENT_DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false

management:
  endpoints:
    web:
      exposure:
        include: health,info